{% set name = "fonticon-materialdesignicons6" %}
{% set version = "6.9.96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b382a662520c095e513e51b8586cb71f9a9ab5f56d6df9fba89f334e0e61b297

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6

test:
  imports:
    - fonticon_mdi6
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/fonticon-materialdesignicons6
  summary: Material Design Icons extension for superqt font icons
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
